name: build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7 # Cairo was tested with this version

      - name: Setup BATS testing framework
        uses: mig4/setup-bats@v1.2.0

      # Fetching cairo as a dependency results in triggering some
      # cairo-run assert
      - name: Install Cairo
        run: |
          pip install cairo-lang==0.3.1

      - name: Test golden tests
        run: |
          make test_bats BATS_ARGS="-j 4"
      
      - name: Test yul tests
        run: |
          make test_yul
